---
- name: Starting configuration
  hosts: all
  vars_files:
  - "{{ lookup('first_found', ['vars/' ~ ansible_facts.distribution | lower ~ '.yml', 'vars/default.yml']) }}"
  vars:
    is_server: false


  roles:
    - { role: 'system', tags: ['system'] }
    - { role: 'neovim', tags: ['neovim'] }
    - { role: 'tmux', tags: ['tmux'] }
    - { role: 'zsh', tags: ['zsh'] }
    - { role: 'fish', tags: ['fish'] }
    - { role: 'streamdeck', tags: ['streamdeck'] }
    - { role: 'zsa', tags: ['zsa', 'moonlander', 'keyboard'] }
