---
- name: Starting macOS configuration
  hosts: all
  vars_files:
  - "{{ lookup('first_found', ['vars/' ~ ansible_facts.distribution | lower ~ '.yml', 'vars/default.yml']) }}"
  - "{{ lookup('first_found', ['vars/hosts/' ~ ansible_facts.hostname ~ '.yml', 'vars/hosts/default.yml']) }}"
  vars:
    is_server: false


  roles:
    - { role: 'system', tags: ['system'] }
    - { role: 'aitools', tags: ['aitools'] }
    - { role: 'ai_memory', tags: ['ai_memory', 'aitools'] }
    - { role: 'codegraph', tags: ['codegraph', 'aitools'] }
    - { role: 'neovim', tags: ['neovim'] }
    - { role: 'tmux', tags: ['tmux'] }
    - { role: 'zsh', tags: ['zsh'], when: machine_profile == 'work' }
    - { role: 'fish', tags: ['fish'], when: machine_profile == 'personal' }
