---
- name: Starting configuration
  hosts: all
  vars_files:
  - "{{ lookup('first_found', [ 'vars/{{ ansible_distribution|lower }}.yml', 'vars/default.yml']) }}"

  roles:
    - { role: 'system', tags: ['system'] }
    - { role: 'neovim', tags: ['neovim'] }
    - { role: 'powerline', tags: ['powerline'] }
    - { role: 'tmux', tags: ['tmux'] }
    - { role: 'weechat', tags: ['weechat'] }
    - { role: 'zsh', tags: ['zsh'] }
