---
- name: Install powerline-status and dependences
  pip:
    name: ['powerline-status', 'psutil']
    executable: pip3
  become: true
  when: ansible_system == 'Darwin'

- name: Install powerline
  package:
    name: powerline
    state: present
  become: true
  when: ansible_system == 'Linux'

- name: Install powerline config.json
  copy:
    src: config.json
    dest: "{{ lookup('env','HOME') }}/.config/powerline"

- name: Install powerline theme files
  copy:
    src: default.json
    dest: "{{ lookup('env', 'HOME') }}/.config/powerline/themes/tmux"
