---
- name: Check if .config directory exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.config"
    state: directory

- include_tasks: system-general.yml

- include_tasks: system-macosx.yml
  when:
    ansible_system == 'Darwin'

- include_tasks: system-linux.yml
  when:
    ansible_system == "Linux"

