---
- name: Check if homebrew is already installed
  stat:
    path: /opt/homebrew/bin/brew
  register: homebrew

- name: Installing homebrew
  script: install-homebrew.sh
  when: not homebrew.stat.exists

- name: Install SVN (required to install some fonts)
  package:
    name: svn
    state: present

- name: Install fonts
  homebrew_cask: name={{ item }} state=present
  with_items:
    - font-droid-sans-mono-for-powerline
    - font-droid-sans-mono-nerd-font
    - font-hack-nerd-font
  ignore_errors: true

- name: Install casks
  homebrew_cask: name={{ item }} state=present
  with_items:
    - hammerspoon

- name: Install packages
  package: name={{ item }} state=present
  with_items:
    - bat
    - coreutils
    - eza
    - fd
    - fzf
    - git-delta
    - git-review
    - npm
    - python
    - tmate
    - virtualenvwrapper

- name: Ensure ~/.hammerspoon directory exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.hammerspoon"
    state: directory

- name: Copy Hammerspoon init.lua
  copy:
    src: hammerspoon-init.lua
    dest: "{{ lookup('env', 'HOME') }}/.hammerspoon/init.lua"
    mode: '0644'

- include_tasks: npm-global.yml
