---
- name: Install system packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - autojump
    - autojump-zsh
    - gcc
    - git
    - git-review
    - python-heatclient
    - python-openstackclient
    - python-virtualenv
    - stow
    - tilix
    - tmate
    - tmux-powerline
    - util-linux-user
  become: true

- name: Install python3 alternatives
  shell: alternatives --install /usr/bin/python python /usr/bin/python3 2
  become: true

- name: Load tilix config to dconf
  shell: dconf load /com/gexperts/Tilix/ < "{{ role_path }}/files/tilix.conf"
