---
- name: Install neovim
  package:
    name: neovim
    state: present
  become: true
  when: ansible_facts.system == 'Linux'

- name: Install neovim
  package:
    name: neovim
    state: present
  when: ansible_facts.system == 'Darwin'

- name: Clean neovim directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/nvim"
    state: absent
  when: cleanup | default(false) | bool

- name: Check if nvim repo exists
  stat:
    path: "{{ ansible_facts.user_dir }}/.config/nvim"
  register: nvim_repo

- name: Clone nvim repo
  git:
    repo: git@github.com:arxcruz/nvim.git
    dest: "{{ ansible_facts.user_dir }}/.config/nvim"
  when: not nvim_repo.stat.exists

- name: Create neovim virtualenv
  shell: virtualenv -p `which python3` "{{ ansible_facts.user_dir }}/.virtualenvs/neovim"

- name: Setup neovim python bindigns
  pip:
    name: ['pynvim', 'flake8', 'pyflakes', 'pycodestyle']
    virtualenv: "{{ ansible_facts.user_dir }}/.virtualenvs/neovim"
    state: present
